### ISSUE TITLE
Dummy iinventory hooks cause mod compatibility issues

### ISSUE THREAD

**Issue by liach** [jaquadro/Chameleon#4]
https://github.com/Railcraft/Railcraft/issues/1303
The base inventory tile entities implement a dummy interface for iinventory (an empty one), causing compability issues.

**Comment by purpleposeidon** [comment]
Railcraft and Hopper Ducts are unable to insert.

**Comment by CovertJaguar** [comment]
Yes, either it needs to be function, or not implement it all.

**Comment by jaquadro** [comment]
The mod used to implement a full IInventory interface, but it had to be dropped.  It was more fully factored out in 1.12.

Probably the reason it continued to exist is because the drawers implement ILockableContainer, and ILockableContainer is an IInventory.  I will have to drop support for that to completely remove IInventory from the tile.

**Comment by jaquadro** [comment]
IInventory and ILockableContainer is removed in Storage Drawers 5.3.0.  This will not be fixed for MC 1.10 or 1.11.
